server:
  port: 8080

spring:
  application:
    name: mall-gateway
  jmx:
    enabled: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: mall-user
          uri: lb://mall-user
          predicates:
            - Path=/api/user/**,/api/admin/user/**,/feign/user/**

        - id: mall-images
          uri: lb://mall-user
          predicates:
            - Path=/images/**

        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**,/api/banner/**,/api/admin/product/**,/api/admin/category/**,/api/admin/banner/**,/feign/product/**

        - id: mall-order
          uri: lb://mall-order
          predicates:
            - Path=/api/cart/**,/api/order/**,/api/admin/order/**,/api/admin/dashboard/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
